"""
robot_formatter.py
------------------
Converts raw LLM-generated test case text into a Robot Framework
.robot file template.

The formatter wraps each block of text in a Robot Framework keyword
stub so the output is immediately usable as a starting template.
"""


ROBOT_HEADER = """\
*** Settings ***
Library    SeleniumLibrary
Library    RequestsLibrary

*** Variables ***
${BASE_URL}    https://your-app-url.com

*** Test Cases ***
"""

ROBOT_FOOTER = """\

*** Keywords ***
# Add shared keywords / reusable steps here
"""


def to_robot_template(raw_test_cases: str) -> str:
    """
    Wrap raw LLM output in a Robot Framework skeleton.

    Each line of the raw output is indented and placed inside a
    single placeholder test case block so QA engineers can quickly
    copy-paste and refine individual cases.

    Args:
        raw_test_cases: Plain-text test cases returned by the LLM.

    Returns:
        A .robot-compatible template string.
    """
    if not raw_test_cases.strip():
        return "# No test cases to format."

    # Indent every line of the raw output for Robot Framework syntax
    indented = "\n".join(
        f"    ...    {line}" if line.strip() else ""
        for line in raw_test_cases.splitlines()
    )

    body = (
        "Generated Test Cases\n"
        "    [Documentation]    Auto-generated by AI Test Case Generator\n"
        "    Log    Review and implement the following test cases:\n"
        f"{indented}\n"
    )

    return ROBOT_HEADER + body + ROBOT_FOOTER


def to_robot_file_content(raw_test_cases: str, story_title: str = "Feature") -> str:
    """
    A slightly richer version that adds a suite-level doc comment.

    Args:
        raw_test_cases: Plain-text test cases from the LLM.
        story_title:    Used as the suite documentation string.

    Returns:
        A complete .robot file content string.
    """
    header = (
        f"*** Settings ***\n"
        f"Documentation    Test suite for: {story_title}\n"
        f"Library          SeleniumLibrary\n"
        f"Library          RequestsLibrary\n\n"
        f"*** Variables ***\n"
        f"${{BASE_URL}}    https://your-app-url.com\n\n"
        f"*** Test Cases ***\n"
    )

    indented = "\n".join(
        f"    ...    {line}" if line.strip() else ""
        for line in raw_test_cases.splitlines()
    )

    body = (
        f"AI Generated Suite For {story_title}\n"
        f"    [Documentation]    Auto-generated — refine before running\n"
        f"    Log    {story_title}\n"
        f"{indented}\n"
    )

    return header + body + ROBOT_FOOTER
